services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hakaton-web
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

